language: java

jdk:
  - oraclejdk8

install: true
script:
  - mvn clean install

after_success:
  - bash <(curl -s https://codecov.io/bash)


cache:
  directories:
    - $HOME/.m2

deploy:
  provider: bintray
  file: "descriptor.json"
  user: $BINTRAY_API_USER
  key: $BINTRAY_API_KEY
  dry-run: true
  on: master
